import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: '#eee' },
  title: { fontSize: 18, fontWeight: 'bold', flex: 1 },
  closeButton: { fontSize: 24, color: '#666' },
  tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee' },
  tab: { flex: 1, padding: 15, alignItems: 'center' },
  activeTab: { borderBottomWidth: 2, borderBottomColor: '#007AFF' },
  tabText: { fontSize: 16, color: '#666' },
  activeTabText: { color: '#007AFF', fontWeight: 'bold' },
  addButton: { backgroundColor: '#4ECDC4', margin: 15, padding: 12, borderRadius: 8, alignItems: 'center' },
  addButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  content: { flex: 1 },
  item: { padding: 15, borderBottomWidth: 1, borderBottomColor: '#eee', position: 'relative' },
  itemTitle: { fontSize: 12, fontWeight: 'bold' },
  itemSubtitle: { fontSize: 10, marginTop: 4 },
  itemDetail: { fontSize: 10, marginTop: 2 },
  editButton: { position: 'absolute', right: 15, top: 15, backgroundColor: '#007AFF', padding: 8, borderRadius: 4 },
  editButtonText: { color: '#fff', fontSize: 12 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  editModal: { backgroundColor: '#fff', width: '90%', maxHeight: '80%', borderRadius: 10, padding: 20 },
  editTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  inputGroup: { marginBottom: 15 },
  inputLabel: { fontSize: 14, fontWeight: 'bold', marginBottom: 5 },
  input: { borderWidth: 1, borderColor: '#ddd', padding: 10, borderRadius: 5 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 5, marginBottom: 5 },
  checkboxLabel: { fontSize: 14, color: '#333' },
  editButtons: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 },
  cancelButton: { backgroundColor: '#ccc', padding: 15, borderRadius: 5, flex: 1, marginRight: 10 },
  saveButton: { backgroundColor: '#007AFF', padding: 15, borderRadius: 5, flex: 1, marginLeft: 10 },
  cancelButtonText: { color: '#333', textAlign: 'center', fontWeight: 'bold' },
  saveButtonText: { color: '#fff', textAlign: 'center', fontWeight: 'bold' },
  deleteSection: { marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#eee' },
  inactiveButton: { backgroundColor: '#FF9500', padding: 15, borderRadius: 5, alignItems: 'center', marginBottom: 10 },
  inactiveButtonText: { color: '#fff', textAlign: 'center', fontWeight: 'bold' },
  deleteButton: { backgroundColor: '#FF6B6B', padding: 15, borderRadius: 5, alignItems: 'center' },
  deleteButtonText: { color: '#fff', textAlign: 'center', fontWeight: 'bold' },
  spreadsheet: { flex: 1 },
  spreadsheetHeader: { padding: 20, borderBottomWidth: 1, borderBottomColor: '#eee' },
  backButton: { fontSize: 16, color: '#007AFF', marginBottom: 10 },
  spreadsheetTitle: { fontSize: 18, fontWeight: 'bold' },
  detailsContainer: { padding: 20 },
  detailRow: { flexDirection: 'row', marginBottom: 10, paddingVertical: 5 },
  detailLabel: { fontSize: 14, fontWeight: 'bold', flex: 1 },
  detailValue: { fontSize: 14, flex: 2 }
});